### ISSUE TITLE
chRat - hamburger menu with 2 pages

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-user-stories#2]
## Value Proposition

As a user
I want to see messages from all users and send message's

## Description

- The hamburger menu display 2 buttons with these you can open 2 more pages with "about" and "imprint".
<img width="250px" alt="hamburger menu logged out" src="https://user-images.githubusercontent.com/55069641/179233162-82fa6090-99df-491f-a1cc-a26c4726c91e.png" />
<img width="250px" alt="about and imprint" src="https://user-images.githubusercontent.com/55069641/179233253-0b3d6ee1-ca51-452c-b29e-14d23c89b151.png" />

## Acceptance Criteria

Maincontent/Chatpage:
- [ ] messages in little chat cards
- [ ] 1 input field -> to submit messages in the message pool
- [ ] 1 button to submit message

## Tasks

(for developers team)

- [ ] global styles
- [ ] create main chat content page
- [ ] design little chat windows that are displayed in the "chatbox"
- [ ] 1 input field with my message
- [ ] 1 button to submit the message
- [ ] use effect to display the chat messages
- [ ] write test to test the send button
- [ ] add to App

**Comment by PReichetanz** [comment]
Hi Chris,

Just one thing: I would suggest to separate the imprint and about page from each other and create two small user stories. The title of both stories should be like the page, e.g. "About page" and "Imprint page", because the hamburger menu is not a feature for itself, but necessary for these pages.

**Comment by chris-yooo** [comment]
ok but i will let the hamburger menu here in this story in, and open a new story with the about page maybe. ty

**Comment by chris-yooo** [comment]
https://github.com/chris-yooo/capstone-user-stories/issues/7 here the littlerer step :D
