### ISSUE TITLE
chRat - aboutpage

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-user-stories#7]
## Value Proposition

As a user
I need a about page
to be able to read them

## Description

<img width="250px" alt="about and imprint" src="https://user-images.githubusercontent.com/55069641/179494799-a8bc8257-850b-4296-9018-0998c3bc8f4f.png" />

## Acceptance Criteria

- [ ] 1 button to open about within the hamburger menu
- [ ] 1 button to go back to chat on the page upper left

## Tasks

(for developers team)

- [ ] 1 button to open about within the hamburger menu
- [ ] look at accessibility !
- [ ] 1 button to go back to chat on the page upper left
- [ ]  look at accessibility !
